apiVersion: v1
kind: Service
metadata:
  labels:
    app: produtos-load-balancer
  name: produtos-load-balancer
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 6002
  selector:
    app: produtos-deployment
  type: LoadBalancer